# nscale-sdk-go
#
# Every client here is generated by oapi-codegen from a spec published in
# nscaledev/openapi. The spec is vendored into this repo (<pkg>/openapi.yaml)
# so `go generate` stays hermetic and works offline, and so a spec change
# shows up as a reviewable diff rather than a silent shift under CI.
#
# `just sync` is the only thing that talks to the network. Everything else
# works from the vendored copies.
#
# Typical refresh:
#     just update              # all packages
#     just update kubernetes   # one package

set shell := ["bash", "-euo", "pipefail", "-c"]

openapi_repo := "nscaledev/openapi"

# Git ref of nscaledev/openapi to pull specs from. Override to pin a review:
#     OPENAPI_REF=<sha> just sync
openapi_ref := env("OPENAPI_REF", "main")

# The single source of truth for where each client's spec comes from:
# "<local package>:<spec directory in nscaledev/openapi>".
#
# <service>/latest/ always mirrors that service's newest stable release, so a
# sync picks up new releases without editing this list. nks-core has not cut a
# stable release yet, so the Kubernetes client tracks its main branch.
specs := "identity:identity/latest region:region/latest storage:storage/latest compute:compute/latest kubernetes:nks-core/main reservation:reservation/latest"

_raw := "https://raw.githubusercontent.com/" + openapi_repo + "/" + openapi_ref

[private]
default:
    @just --list --unsorted

# Print each package and the upstream spec it tracks.
[group('spec')]
sources:
    #!/usr/bin/env bash
    set -euo pipefail
    for entry in {{ specs }}; do
        printf '%-12s <- %s/%s/openapi.yaml\n' "${entry%%:*}" "{{ openapi_repo }}@{{ openapi_ref }}" "${entry#*:}"
    done

# Fetch vendored spec(s) from nscaledev/openapi. PKG defaults to every package.
[group('spec')]
sync pkg="":
    #!/usr/bin/env bash
    set -euo pipefail
    matched=0
    for entry in {{ specs }}; do
        name="${entry%%:*}" path="${entry#*:}"
        if [[ -n "{{ pkg }}" && "$name" != "{{ pkg }}" ]]; then continue; fi
        matched=1
        echo "==> $name <- {{ openapi_repo }}@{{ openapi_ref }}/$path"
        curl -sfL "{{ _raw }}/$path/openapi.yaml" -o "$name/openapi.yaml"
    done
    if [[ "$matched" == 0 ]]; then
        echo "unknown package '{{ pkg }}'; run 'just sources' for the list" >&2
        exit 1
    fi

# Regenerate client(s) from the vendored specs. Hermetic; no network.
[group('spec')]
generate pkg="":
    #!/usr/bin/env bash
    set -euo pipefail
    if [[ -n "{{ pkg }}" ]]; then
        test -d "{{ pkg }}" || { echo "unknown package '{{ pkg }}'; run 'just sources' for the list" >&2; exit 1; }
        go generate "./{{ pkg }}/..."
    else
        go generate ./...
    fi

# Refresh spec(s) from upstream, regenerate, and confirm the result builds.
[group('spec')]
update pkg="": (sync pkg) (generate pkg) build

# Report which vendored specs have drifted from upstream. Read-only.
[group('spec')]
drift:
    #!/usr/bin/env bash
    set -euo pipefail
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' EXIT
    drifted=0
    for entry in {{ specs }}; do
        name="${entry%%:*}" path="${entry#*:}"
        curl -sfL "{{ _raw }}/$path/openapi.yaml" -o "$tmp/$name.yaml"
        if diff -q "$tmp/$name.yaml" "$name/openapi.yaml" >/dev/null; then
            echo "$name: up to date"
        else
            changed="$(diff -U0 "$name/openapi.yaml" "$tmp/$name.yaml" | grep -cE '^[-+][^-+]' || true)"
            echo "$name: DRIFTED ($changed changed lines) — run 'just update $name'"
            drifted=$((drifted + 1))
        fi
    done
    if [[ "$drifted" -gt 0 ]]; then exit 1; fi

# Fail if the committed *.gen.go files don't match what the vendored specs generate.
[group('check')]
verify-generated: generate
    #!/usr/bin/env bash
    set -euo pipefail
    if ! git diff --quiet -- '*.gen.go'; then
        echo "generated code is stale; run 'just generate' and commit the result" >&2
        git --no-pager diff --stat -- '*.gen.go' >&2
        exit 1
    fi
    echo "generated code is up to date"

[group('check')]
build:
    go build ./...

[group('check')]
test:
    go test ./... -count=1

[group('check')]
fmt:
    gofmt -l -w .

[group('check')]
tidy:
    go mod tidy

# Everything CI runs.
[group('check')]
check: build test verify-generated
