// Package storage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package storage

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	Oauth2AuthenticationScopes = "oauth2Authentication.Scopes"
)

// Defines values for BearerMethod.
const (
	Body   BearerMethod = "body"
	Header BearerMethod = "header"
	Query  BearerMethod = "query"
)

// Defines values for ErrorError.
const (
	AccessDenied          ErrorError = "access_denied"
	Conflict              ErrorError = "conflict"
	Forbidden             ErrorError = "forbidden"
	InvalidRequest        ErrorError = "invalid_request"
	MethodNotAllowed      ErrorError = "method_not_allowed"
	NotFound              ErrorError = "not_found"
	RequestEntityTooLarge ErrorError = "request_entity_too_large"
	ServerError           ErrorError = "server_error"
	UnprocessableContent  ErrorError = "unprocessable_content"
	UnsupportedMediaType  ErrorError = "unsupported_media_type"
)

// Defines values for ObjectStorageEndpointClassSupportedEndpointType.
const (
	Private ObjectStorageEndpointClassSupportedEndpointType = "private"
	Public  ObjectStorageEndpointClassSupportedEndpointType = "public"
)

// Defines values for ResourceHealthStatus.
const (
	ResourceHealthStatusDegraded ResourceHealthStatus = "degraded"
	ResourceHealthStatusError    ResourceHealthStatus = "error"
	ResourceHealthStatusHealthy  ResourceHealthStatus = "healthy"
	ResourceHealthStatusUnknown  ResourceHealthStatus = "unknown"
)

// Defines values for ResourceProvisioningStatus.
const (
	ResourceProvisioningStatusDeprovisioning ResourceProvisioningStatus = "deprovisioning"
	ResourceProvisioningStatusError          ResourceProvisioningStatus = "error"
	ResourceProvisioningStatusPending        ResourceProvisioningStatus = "pending"
	ResourceProvisioningStatusProvisioned    ResourceProvisioningStatus = "provisioned"
	ResourceProvisioningStatusProvisioning   ResourceProvisioningStatus = "provisioning"
	ResourceProvisioningStatusUnknown        ResourceProvisioningStatus = "unknown"
)

// AuthorizationServerList List of authorization servers that can grant access to the resource.
type AuthorizationServerList = []string

// BearerMethod Bearer token transport method
type BearerMethod string

// BearerMethodList A set of bearer token transport methods supported by the protected endpoint.
type BearerMethodList = []BearerMethod

// Error Generic error message, compatible with oauth2.
type Error struct {
	// Error A terse error string expanding on the HTTP error code. Errors are based on the OAuth 2.02 specification, but are expanded with proprietary status codes for APIs other than those specified by OAuth 2.02.
	Error ErrorError `json:"error"`

	// ErrorDescription Verbose message describing the error.
	ErrorDescription string `json:"error_description"`

	// TraceId Unique trace identifier for the request.
	TraceId *string `json:"trace_id,omitempty"`
}

// ErrorError A terse error string expanding on the HTTP error code. Errors are based on the OAuth 2.02 specification, but are expanded with proprietary status codes for APIs other than those specified by OAuth 2.02.
type ErrorError string

// KubernetesLabelValue A valid Kubernetes label value, typically used for resource names that can be
// indexed in the database.
type KubernetesLabelValue = string

// KubernetesNameParameter A Kubernetes name. Must be a valid DNS containing only lower case characters, numbers or hyphens, start and end with a character or number, and be at most 63 characters in length.
type KubernetesNameParameter = string

// ObjectStorageAccessKeyCreate An object storage access key create request.
type ObjectStorageAccessKeyCreate struct {
	// Metadata Metadata required for all API resource reads and writes.
	Metadata ResourceMetadata `json:"metadata"`

	// Spec An object storage access key create specification.
	Spec ObjectStorageAccessKeyCreateSpec `json:"spec"`
}

// ObjectStorageAccessKeyCreateResponseBody An object storage access key create response.
type ObjectStorageAccessKeyCreateResponseBody struct {
	// Metadata Metadata required by project scoped resource reads.
	Metadata ProjectScopedResourceReadMetadata `json:"metadata"`

	// Spec An object storage access key create response specification.
	Spec ObjectStorageAccessKeyCreateResponseSpec `json:"spec"`
}

// ObjectStorageAccessKeyCreateResponseSpec An object storage access key create response specification.
type ObjectStorageAccessKeyCreateResponseSpec struct {
	// AccessKeyId The S3 access key identifier.
	AccessKeyId string `json:"accessKeyId"`

	// IdentityPolicy The identity policy name associated with the access key.
	IdentityPolicy string `json:"identityPolicy"`

	// Secret The generated secret for the access key. This value is returned only once when the access key is created.
	Secret string `json:"secret"`
}

// ObjectStorageAccessKeyCreateSpec An object storage access key create specification.
type ObjectStorageAccessKeyCreateSpec struct {
	// IdentityPolicy The identity policy name associated with the access key.
	IdentityPolicy string `json:"identityPolicy"`
}

// ObjectStorageAccessKeyListRead A list of object storage access keys.
type ObjectStorageAccessKeyListRead = []ObjectStorageAccessKeyRead

// ObjectStorageAccessKeyRead An object storage access key associated with an object storage endpoint.
type ObjectStorageAccessKeyRead struct {
	// Metadata Metadata required by project scoped resource reads.
	Metadata ProjectScopedResourceReadMetadata `json:"metadata"`

	// Spec An object storage access key specification.
	Spec ObjectStorageAccessKeySpec `json:"spec"`
}

// ObjectStorageAccessKeySpec An object storage access key specification.
type ObjectStorageAccessKeySpec struct {
	// AccessKeyId The S3 access key identifier.
	AccessKeyId *string `json:"accessKeyId"`

	// IdentityPolicy The identity policy name associated with the access key.
	IdentityPolicy string `json:"identityPolicy"`
}

// ObjectStorageEndpointClassListRead A list of object storage endpoint classes.
type ObjectStorageEndpointClassListRead = []ObjectStorageEndpointClassRead

// ObjectStorageEndpointClassRead An object storage endpoint class.
type ObjectStorageEndpointClassRead struct {
	// Metadata Metadata required by all resource reads.
	Metadata ResourceReadMetadata `json:"metadata"`

	// Spec An object storage endpoint class specification.
	Spec ObjectStorageEndpointClassSpec `json:"spec"`
}

// ObjectStorageEndpointClassSpec An object storage endpoint class specification.
type ObjectStorageEndpointClassSpec struct {
	// RegionId The region an object storage endpoint class is provisioned in.
	RegionId string `json:"regionId"`

	// SupportedEndpointType The endpoint exposure types supported by the object storage endpoint class.
	SupportedEndpointType []ObjectStorageEndpointClassSupportedEndpointType `json:"supportedEndpointType"`
}

// ObjectStorageEndpointClassSupportedEndpointType An endpoint exposure type supported by the object storage endpoint class.
type ObjectStorageEndpointClassSupportedEndpointType string

// ObjectStorageEndpointCreate An object storage endpoint create request.
type ObjectStorageEndpointCreate struct {
	// Metadata Metadata required for all API resource reads and writes.
	Metadata ResourceMetadata `json:"metadata"`
	Spec     struct {
		// IdentityPolicies A list of identity policies configured for an object storage endpoint.
		IdentityPolicies *ObjectStorageIdentityPolicyList `json:"identityPolicies,omitempty"`

		// ObjectStorageEndpointClassId The immutable object storage endpoint class selected when the endpoint was created.
		ObjectStorageEndpointClassId string `json:"objectStorageEndpointClassId"`

		// OrganizationId The organization to provision the resource in.
		OrganizationId string `json:"organizationId"`

		// ProjectId The project to provision the resource in.
		ProjectId string `json:"projectId"`

		// RegionId The region to provision the object storage endpoint in.
		RegionId string `json:"regionId"`
	} `json:"spec"`
}

// ObjectStorageEndpointExposureDetailsStatus Connection details for a specific exposure mode.
type ObjectStorageEndpointExposureDetailsStatus struct {
	// DnsName The DNS hostname clients use to reach the endpoint.
	DnsName string `json:"dnsName"`
}

// ObjectStorageEndpointExposureStatus The externally reachable endpoints for an object storage endpoint.
type ObjectStorageEndpointExposureStatus struct {
	// Public Connection details for a specific exposure mode.
	Public *ObjectStorageEndpointExposureDetailsStatus `json:"public,omitempty"`
}

// ObjectStorageEndpointList A list of object storage endpoints.
type ObjectStorageEndpointList = []ObjectStorageEndpointRead

// ObjectStorageEndpointRead An S3-compatible object storage endpoint that allows users to self-service create buckets through the access it exposes.
type ObjectStorageEndpointRead struct {
	// Metadata Metadata required by project scoped resource reads.
	Metadata ProjectScopedResourceReadMetadata `json:"metadata"`

	// Spec An object storage endpoint specification.
	Spec ObjectStorageEndpointSpec `json:"spec"`

	// Status The observed status of an object storage endpoint.
	Status ObjectStorageEndpointStatus `json:"status"`
}

// ObjectStorageEndpointSpec An object storage endpoint specification.
type ObjectStorageEndpointSpec struct {
	// IdentityPolicies A list of identity policies configured for an object storage endpoint.
	IdentityPolicies *ObjectStorageIdentityPolicyList `json:"identityPolicies,omitempty"`

	// ObjectStorageEndpointClassId The immutable object storage endpoint class selected when the endpoint was created.
	ObjectStorageEndpointClassId string `json:"objectStorageEndpointClassId"`
}

// ObjectStorageEndpointStatus The observed status of an object storage endpoint.
type ObjectStorageEndpointStatus struct {
	// Exposure The externally reachable endpoints for an object storage endpoint.
	Exposure *ObjectStorageEndpointExposureStatus `json:"exposure,omitempty"`

	// RegionId The region the object storage endpoint is provisioned in.
	RegionId string `json:"regionId"`
}

// ObjectStorageEndpointUpdate An object storage endpoint update request. The selected endpoint class is immutable, but the configured identity policies may be replaced as a full list.
type ObjectStorageEndpointUpdate struct {
	// Metadata Metadata required for all API resource reads and writes.
	Metadata ResourceMetadata `json:"metadata"`

	// Spec The mutable portion of an object storage endpoint specification. When identityPolicies is present in an update request, it replaces the full set of configured policies.
	Spec *ObjectStorageEndpointUpdateSpec `json:"spec,omitempty"`
}

// ObjectStorageEndpointUpdateSpec The mutable portion of an object storage endpoint specification. When identityPolicies is present in an update request, it replaces the full set of configured policies.
type ObjectStorageEndpointUpdateSpec struct {
	// IdentityPolicies A list of identity policies configured for an object storage endpoint.
	IdentityPolicies *ObjectStorageIdentityPolicyList `json:"identityPolicies,omitempty"`
}

// ObjectStorageIdentityPolicyDocument A provider-specific identity policy document represented as an arbitrary JSON object.
type ObjectStorageIdentityPolicyDocument map[string]interface{}

// ObjectStorageIdentityPolicyList A list of identity policies configured for an object storage endpoint.
type ObjectStorageIdentityPolicyList = []ObjectStorageIdentityPolicySpec

// ObjectStorageIdentityPolicySpec A named identity policy configured for an object storage endpoint.
type ObjectStorageIdentityPolicySpec struct {
	// Document A provider-specific identity policy document represented as an arbitrary JSON object.
	Document ObjectStorageIdentityPolicyDocument `json:"document"`

	// Name The identity policy name. Names must be unique within the object storage endpoint.
	Name string `json:"name"`
}

// OpenidProtectedResource OpenID athentication server discovery configuration.
type OpenidProtectedResource struct {
	// AuthorizationServers List of authorization servers that can grant access to the resource.
	AuthorizationServers AuthorizationServerList `json:"authorization_servers"`

	// BearerMethodsSupported A set of bearer token transport methods supported by the protected endpoint.
	BearerMethodsSupported BearerMethodList `json:"bearer_methods_supported"`

	// Resource The protected resource's scheme and hostname.
	Resource string `json:"resource"`

	// ScopesSupported A set of OIDC scopes that are required for authorization.
	ScopesSupported ScopeList `json:"scopes_supported"`
}

// OrganizationScopedResourceReadMetadata defines model for organizationScopedResourceReadMetadata.
type OrganizationScopedResourceReadMetadata struct {
	// CreatedBy The user who created the resource.
	CreatedBy *string `json:"createdBy,omitempty"`

	// CreationTime The time the resource was created.
	CreationTime time.Time `json:"creationTime"`

	// DeletionTime The time the resource was deleted.
	DeletionTime *time.Time `json:"deletionTime,omitempty"`

	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// HealthStatus The health state of a resource.
	HealthStatus ResourceHealthStatus `json:"healthStatus"`

	// Id The unique resource ID.
	Id string `json:"id"`

	// ModifiedBy The user who updated the resource.
	ModifiedBy *string `json:"modifiedBy,omitempty"`

	// ModifiedTime The time a resource was updated.
	ModifiedTime *time.Time `json:"modifiedTime,omitempty"`

	// Name A valid Kubernetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// OrganizationId The organization identifier the resource belongs to.
	OrganizationId string `json:"organizationId"`

	// ProvisioningStatus The provisioning state of a resource.
	ProvisioningStatus ResourceProvisioningStatus `json:"provisioningStatus"`

	// Tags A list of tags.
	Tags *TagList `json:"tags,omitempty"`
}

// ProjectScopedResourceReadMetadata defines model for projectScopedResourceReadMetadata.
type ProjectScopedResourceReadMetadata struct {
	// CreatedBy The user who created the resource.
	CreatedBy *string `json:"createdBy,omitempty"`

	// CreationTime The time the resource was created.
	CreationTime time.Time `json:"creationTime"`

	// DeletionTime The time the resource was deleted.
	DeletionTime *time.Time `json:"deletionTime,omitempty"`

	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// HealthStatus The health state of a resource.
	HealthStatus ResourceHealthStatus `json:"healthStatus"`

	// Id The unique resource ID.
	Id string `json:"id"`

	// ModifiedBy The user who updated the resource.
	ModifiedBy *string `json:"modifiedBy,omitempty"`

	// ModifiedTime The time a resource was updated.
	ModifiedTime *time.Time `json:"modifiedTime,omitempty"`

	// Name A valid Kubernetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// OrganizationId The organization identifier the resource belongs to.
	OrganizationId string `json:"organizationId"`

	// ProjectId The project identifier the resource belongs to.
	ProjectId string `json:"projectId"`

	// ProvisioningStatus The provisioning state of a resource.
	ProvisioningStatus ResourceProvisioningStatus `json:"provisioningStatus"`

	// Tags A list of tags.
	Tags *TagList `json:"tags,omitempty"`
}

// ResourceHealthStatus The health state of a resource.
type ResourceHealthStatus string

// ResourceMetadata Metadata required for all API resource reads and writes.
type ResourceMetadata struct {
	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// Name A valid Kubernetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// Tags A list of tags.
	Tags *TagList `json:"tags,omitempty"`
}

// ResourceProvisioningStatus The provisioning state of a resource.
type ResourceProvisioningStatus string

// ResourceReadMetadata defines model for resourceReadMetadata.
type ResourceReadMetadata struct {
	// CreatedBy The user who created the resource.
	CreatedBy *string `json:"createdBy,omitempty"`

	// CreationTime The time the resource was created.
	CreationTime time.Time `json:"creationTime"`

	// DeletionTime The time the resource was deleted.
	DeletionTime *time.Time `json:"deletionTime,omitempty"`

	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// HealthStatus The health state of a resource.
	HealthStatus ResourceHealthStatus `json:"healthStatus"`

	// Id The unique resource ID.
	Id string `json:"id"`

	// ModifiedBy The user who updated the resource.
	ModifiedBy *string `json:"modifiedBy,omitempty"`

	// ModifiedTime The time a resource was updated.
	ModifiedTime *time.Time `json:"modifiedTime,omitempty"`

	// Name A valid Kubernetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// ProvisioningStatus The provisioning state of a resource.
	ProvisioningStatus ResourceProvisioningStatus `json:"provisioningStatus"`

	// Tags A list of tags.
	Tags *TagList `json:"tags,omitempty"`
}

// ScopeList A set of OIDC scopes that are required for authorization.
type ScopeList = []string

// ServiceVersionRead Build version information for the running service, stamped into the
// binary at release time.  Developer builds report version 0.0.0.
type ServiceVersionRead struct {
	// Name The service application name.
	Name string `json:"name"`

	// Version The service release version, e.g. v1.2.3.
	Version string `json:"version"`
}

// StaticResourceMetadata defines model for staticResourceMetadata.
type StaticResourceMetadata struct {
	// CreatedBy The user who created the resource.
	CreatedBy *string `json:"createdBy,omitempty"`

	// CreationTime The time the resource was created.
	CreationTime time.Time `json:"creationTime"`

	// Description The resource description, this optionally augments the name with more context.
	Description *string `json:"description,omitempty"`

	// Id The unique resource ID.
	Id string `json:"id"`

	// ModifiedBy The user who updated the resource.
	ModifiedBy *string `json:"modifiedBy,omitempty"`

	// ModifiedTime The time a resource was updated.
	ModifiedTime *time.Time `json:"modifiedTime,omitempty"`

	// Name A valid Kubernetes label value, typically used for resource names that can be
	// indexed in the database.
	Name KubernetesLabelValue `json:"name"`

	// Tags A list of tags.
	Tags *TagList `json:"tags,omitempty"`
}

// Tag A tag mapping arbitrary names to values.  These have no special meaning
// for any component are are intended for use by end users to add additional
// context to a resource, for example to categorize it.
type Tag struct {
	// Name A unique tag name.
	Name string `json:"name"`

	// Value The value of the tag.
	Value string `json:"value"`
}

// TagList A list of tags.
type TagList = []Tag

// ObjectStorageAccessKeyIDParameter A Kubernetes name. Must be a valid DNS containing only lower case characters, numbers or hyphens, start and end with a character or number, and be at most 63 characters in length.
type ObjectStorageAccessKeyIDParameter = KubernetesNameParameter

// ObjectStorageEndpointIDParameter A Kubernetes name. Must be a valid DNS containing only lower case characters, numbers or hyphens, start and end with a character or number, and be at most 63 characters in length.
type ObjectStorageEndpointIDParameter = KubernetesNameParameter

// OrganizationIDQueryParameter defines model for organizationIDQueryParameter.
type OrganizationIDQueryParameter = []string

// ProjectIDQueryParameter defines model for projectIDQueryParameter.
type ProjectIDQueryParameter = []string

// RegionIDQueryParameter defines model for regionIDQueryParameter.
type RegionIDQueryParameter = []string

// TagSelectorParameter defines model for tagSelectorParameter.
type TagSelectorParameter = []string

// BadRequestResponse Generic error message, compatible with oauth2.
type BadRequestResponse = Error

// ConflictResponse Generic error message, compatible with oauth2.
type ConflictResponse = Error

// ForbiddenResponse Generic error message, compatible with oauth2.
type ForbiddenResponse = Error

// InternalServerErrorResponse Generic error message, compatible with oauth2.
type InternalServerErrorResponse = Error

// NotFoundResponse Generic error message, compatible with oauth2.
type NotFoundResponse = Error

// ObjectStorageAccessKeyCreateResponse An object storage access key create response.
type ObjectStorageAccessKeyCreateResponse = ObjectStorageAccessKeyCreateResponseBody

// ObjectStorageAccessKeyListResponse A list of object storage access keys.
type ObjectStorageAccessKeyListResponse = ObjectStorageAccessKeyListRead

// ObjectStorageAccessKeyResponse An object storage access key associated with an object storage endpoint.
type ObjectStorageAccessKeyResponse = ObjectStorageAccessKeyRead

// ObjectStorageEndpointClassListResponse A list of object storage endpoint classes.
type ObjectStorageEndpointClassListResponse = ObjectStorageEndpointClassListRead

// ObjectStorageEndpointListResponse A list of object storage endpoints.
type ObjectStorageEndpointListResponse = ObjectStorageEndpointList

// ObjectStorageEndpointResponse An S3-compatible object storage endpoint that allows users to self-service create buckets through the access it exposes.
type ObjectStorageEndpointResponse = ObjectStorageEndpointRead

// OpenidProtectedResourceResponse OpenID athentication server discovery configuration.
type OpenidProtectedResourceResponse = OpenidProtectedResource

// ServiceVersionResponse Build version information for the running service, stamped into the
// binary at release time.  Developer builds report version 0.0.0.
type ServiceVersionResponse = ServiceVersionRead

// UnauthorizedResponse Generic error message, compatible with oauth2.
type UnauthorizedResponse = Error

// UnprocessableContentResponse Generic error message, compatible with oauth2.
type UnprocessableContentResponse = Error

// ObjectStorageAccessKeyCreateRequest An object storage access key create request.
type ObjectStorageAccessKeyCreateRequest = ObjectStorageAccessKeyCreate

// ObjectStorageEndpointCreateRequest An object storage endpoint create request.
type ObjectStorageEndpointCreateRequest = ObjectStorageEndpointCreate

// ObjectStorageEndpointUpdateRequest An object storage endpoint update request. The selected endpoint class is immutable, but the configured identity policies may be replaced as a full list.
type ObjectStorageEndpointUpdateRequest = ObjectStorageEndpointUpdate

// GetApiV1ObjectstorageendpointclassesParams defines parameters for GetApiV1Objectstorageendpointclasses.
type GetApiV1ObjectstorageendpointclassesParams struct {
	// RegionID Allows resources to be filtered by region.
	RegionID *RegionIDQueryParameter `form:"regionID,omitempty" json:"regionID,omitempty"`
}

// GetApiV1ObjectstorageendpointsParams defines parameters for GetApiV1Objectstorageendpoints.
type GetApiV1ObjectstorageendpointsParams struct {
	// Tag A set of tags to match against resources in the form "name=value",
	// thus when encoded you get "?tag=foo%3Dcat&tag=bar%3Ddog".
	Tag *TagSelectorParameter `form:"tag,omitempty" json:"tag,omitempty"`

	// OrganizationID Allows resources to be filtered by organization.
	OrganizationID *OrganizationIDQueryParameter `form:"organizationID,omitempty" json:"organizationID,omitempty"`

	// ProjectID Allows resources to be filtered by project.
	ProjectID *ProjectIDQueryParameter `form:"projectID,omitempty" json:"projectID,omitempty"`

	// RegionID Allows resources to be filtered by region.
	RegionID *RegionIDQueryParameter `form:"regionID,omitempty" json:"regionID,omitempty"`
}

// PostApiV1ObjectstorageendpointsJSONRequestBody defines body for PostApiV1Objectstorageendpoints for application/json ContentType.
type PostApiV1ObjectstorageendpointsJSONRequestBody = ObjectStorageEndpointCreate

// PutApiV1ObjectstorageendpointsObjectStorageEndpointIDJSONRequestBody defines body for PutApiV1ObjectstorageendpointsObjectStorageEndpointID for application/json ContentType.
type PutApiV1ObjectstorageendpointsObjectStorageEndpointIDJSONRequestBody = ObjectStorageEndpointUpdate

// PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysJSONRequestBody defines body for PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeys for application/json ContentType.
type PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysJSONRequestBody = ObjectStorageAccessKeyCreate

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetApiV1Objectstorageendpointclasses request
	GetApiV1Objectstorageendpointclasses(ctx context.Context, params *GetApiV1ObjectstorageendpointclassesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1Objectstorageendpoints request
	GetApiV1Objectstorageendpoints(ctx context.Context, params *GetApiV1ObjectstorageendpointsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1ObjectstorageendpointsWithBody request with any body
	PostApiV1ObjectstorageendpointsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1Objectstorageendpoints(ctx context.Context, body PostApiV1ObjectstorageendpointsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiV1ObjectstorageendpointsObjectStorageEndpointID request
	DeleteApiV1ObjectstorageendpointsObjectStorageEndpointID(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1ObjectstorageendpointsObjectStorageEndpointID request
	GetApiV1ObjectstorageendpointsObjectStorageEndpointID(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiV1ObjectstorageendpointsObjectStorageEndpointIDWithBody request with any body
	PutApiV1ObjectstorageendpointsObjectStorageEndpointIDWithBody(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutApiV1ObjectstorageendpointsObjectStorageEndpointID(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, body PutApiV1ObjectstorageendpointsObjectStorageEndpointIDJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeys request
	GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeys(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithBody request with any body
	PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithBody(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeys(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, body PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyID request
	DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyID(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, objectStorageAccessKeyID ObjectStorageAccessKeyIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyID request
	GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyID(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, objectStorageAccessKeyID ObjectStorageAccessKeyIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiVersion request
	GetApiVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetApiV1Objectstorageendpointclasses(ctx context.Context, params *GetApiV1ObjectstorageendpointclassesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ObjectstorageendpointclassesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1Objectstorageendpoints(ctx context.Context, params *GetApiV1ObjectstorageendpointsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ObjectstorageendpointsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1ObjectstorageendpointsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ObjectstorageendpointsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1Objectstorageendpoints(ctx context.Context, body PostApiV1ObjectstorageendpointsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ObjectstorageendpointsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiV1ObjectstorageendpointsObjectStorageEndpointID(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDRequest(c.Server, objectStorageEndpointID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1ObjectstorageendpointsObjectStorageEndpointID(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ObjectstorageendpointsObjectStorageEndpointIDRequest(c.Server, objectStorageEndpointID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiV1ObjectstorageendpointsObjectStorageEndpointIDWithBody(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1ObjectstorageendpointsObjectStorageEndpointIDRequestWithBody(c.Server, objectStorageEndpointID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiV1ObjectstorageendpointsObjectStorageEndpointID(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, body PutApiV1ObjectstorageendpointsObjectStorageEndpointIDJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiV1ObjectstorageendpointsObjectStorageEndpointIDRequest(c.Server, objectStorageEndpointID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeys(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysRequest(c.Server, objectStorageEndpointID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithBody(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysRequestWithBody(c.Server, objectStorageEndpointID, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeys(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, body PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysRequest(c.Server, objectStorageEndpointID, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyID(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, objectStorageAccessKeyID ObjectStorageAccessKeyIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDRequest(c.Server, objectStorageEndpointID, objectStorageAccessKeyID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyID(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, objectStorageAccessKeyID ObjectStorageAccessKeyIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDRequest(c.Server, objectStorageEndpointID, objectStorageAccessKeyID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiVersion(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiVersionRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetApiV1ObjectstorageendpointclassesRequest generates requests for GetApiV1Objectstorageendpointclasses
func NewGetApiV1ObjectstorageendpointclassesRequest(server string, params *GetApiV1ObjectstorageendpointclassesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/objectstorageendpointclasses")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.RegionID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "regionID", runtime.ParamLocationQuery, *params.RegionID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV1ObjectstorageendpointsRequest generates requests for GetApiV1Objectstorageendpoints
func NewGetApiV1ObjectstorageendpointsRequest(server string, params *GetApiV1ObjectstorageendpointsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/objectstorageendpoints")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Tag != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tag", runtime.ParamLocationQuery, *params.Tag); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrganizationID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organizationID", runtime.ParamLocationQuery, *params.OrganizationID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ProjectID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "projectID", runtime.ParamLocationQuery, *params.ProjectID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RegionID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "regionID", runtime.ParamLocationQuery, *params.RegionID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1ObjectstorageendpointsRequest calls the generic PostApiV1Objectstorageendpoints builder with application/json body
func NewPostApiV1ObjectstorageendpointsRequest(server string, body PostApiV1ObjectstorageendpointsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1ObjectstorageendpointsRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiV1ObjectstorageendpointsRequestWithBody generates requests for PostApiV1Objectstorageendpoints with any type of body
func NewPostApiV1ObjectstorageendpointsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/objectstorageendpoints")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDRequest generates requests for DeleteApiV1ObjectstorageendpointsObjectStorageEndpointID
func NewDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDRequest(server string, objectStorageEndpointID ObjectStorageEndpointIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "objectStorageEndpointID", runtime.ParamLocationPath, objectStorageEndpointID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/objectstorageendpoints/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV1ObjectstorageendpointsObjectStorageEndpointIDRequest generates requests for GetApiV1ObjectstorageendpointsObjectStorageEndpointID
func NewGetApiV1ObjectstorageendpointsObjectStorageEndpointIDRequest(server string, objectStorageEndpointID ObjectStorageEndpointIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "objectStorageEndpointID", runtime.ParamLocationPath, objectStorageEndpointID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/objectstorageendpoints/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutApiV1ObjectstorageendpointsObjectStorageEndpointIDRequest calls the generic PutApiV1ObjectstorageendpointsObjectStorageEndpointID builder with application/json body
func NewPutApiV1ObjectstorageendpointsObjectStorageEndpointIDRequest(server string, objectStorageEndpointID ObjectStorageEndpointIDParameter, body PutApiV1ObjectstorageendpointsObjectStorageEndpointIDJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutApiV1ObjectstorageendpointsObjectStorageEndpointIDRequestWithBody(server, objectStorageEndpointID, "application/json", bodyReader)
}

// NewPutApiV1ObjectstorageendpointsObjectStorageEndpointIDRequestWithBody generates requests for PutApiV1ObjectstorageendpointsObjectStorageEndpointID with any type of body
func NewPutApiV1ObjectstorageendpointsObjectStorageEndpointIDRequestWithBody(server string, objectStorageEndpointID ObjectStorageEndpointIDParameter, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "objectStorageEndpointID", runtime.ParamLocationPath, objectStorageEndpointID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/objectstorageendpoints/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysRequest generates requests for GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeys
func NewGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysRequest(server string, objectStorageEndpointID ObjectStorageEndpointIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "objectStorageEndpointID", runtime.ParamLocationPath, objectStorageEndpointID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/objectstorageendpoints/%s/accesskeys", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysRequest calls the generic PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeys builder with application/json body
func NewPostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysRequest(server string, objectStorageEndpointID ObjectStorageEndpointIDParameter, body PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysRequestWithBody(server, objectStorageEndpointID, "application/json", bodyReader)
}

// NewPostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysRequestWithBody generates requests for PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeys with any type of body
func NewPostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysRequestWithBody(server string, objectStorageEndpointID ObjectStorageEndpointIDParameter, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "objectStorageEndpointID", runtime.ParamLocationPath, objectStorageEndpointID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/objectstorageendpoints/%s/accesskeys", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDRequest generates requests for DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyID
func NewDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDRequest(server string, objectStorageEndpointID ObjectStorageEndpointIDParameter, objectStorageAccessKeyID ObjectStorageAccessKeyIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "objectStorageEndpointID", runtime.ParamLocationPath, objectStorageEndpointID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "objectStorageAccessKeyID", runtime.ParamLocationPath, objectStorageAccessKeyID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/objectstorageendpoints/%s/accesskeys/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDRequest generates requests for GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyID
func NewGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDRequest(server string, objectStorageEndpointID ObjectStorageEndpointIDParameter, objectStorageAccessKeyID ObjectStorageAccessKeyIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "objectStorageEndpointID", runtime.ParamLocationPath, objectStorageEndpointID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "objectStorageAccessKeyID", runtime.ParamLocationPath, objectStorageAccessKeyID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/objectstorageendpoints/%s/accesskeys/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiVersionRequest generates requests for GetApiVersion
func NewGetApiVersionRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/version")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetApiV1ObjectstorageendpointclassesWithResponse request
	GetApiV1ObjectstorageendpointclassesWithResponse(ctx context.Context, params *GetApiV1ObjectstorageendpointclassesParams, reqEditors ...RequestEditorFn) (*GetApiV1ObjectstorageendpointclassesResponse, error)

	// GetApiV1ObjectstorageendpointsWithResponse request
	GetApiV1ObjectstorageendpointsWithResponse(ctx context.Context, params *GetApiV1ObjectstorageendpointsParams, reqEditors ...RequestEditorFn) (*GetApiV1ObjectstorageendpointsResponse, error)

	// PostApiV1ObjectstorageendpointsWithBodyWithResponse request with any body
	PostApiV1ObjectstorageendpointsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ObjectstorageendpointsResponse, error)

	PostApiV1ObjectstorageendpointsWithResponse(ctx context.Context, body PostApiV1ObjectstorageendpointsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ObjectstorageendpointsResponse, error)

	// DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse request
	DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse, error)

	// GetApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse request
	GetApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*GetApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse, error)

	// PutApiV1ObjectstorageendpointsObjectStorageEndpointIDWithBodyWithResponse request with any body
	PutApiV1ObjectstorageendpointsObjectStorageEndpointIDWithBodyWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse, error)

	PutApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, body PutApiV1ObjectstorageendpointsObjectStorageEndpointIDJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse, error)

	// GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithResponse request
	GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse, error)

	// PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithBodyWithResponse request with any body
	PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithBodyWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse, error)

	PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, body PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse, error)

	// DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDWithResponse request
	DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, objectStorageAccessKeyID ObjectStorageAccessKeyIDParameter, reqEditors ...RequestEditorFn) (*DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse, error)

	// GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDWithResponse request
	GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, objectStorageAccessKeyID ObjectStorageAccessKeyIDParameter, reqEditors ...RequestEditorFn) (*GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse, error)

	// GetApiVersionWithResponse request
	GetApiVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiVersionResponse, error)
}

type GetApiV1ObjectstorageendpointclassesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ObjectStorageEndpointClassListResponse
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON500      *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV1ObjectstorageendpointclassesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ObjectstorageendpointclassesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1ObjectstorageendpointsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ObjectStorageEndpointListResponse
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON500      *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV1ObjectstorageendpointsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ObjectstorageendpointsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1ObjectstorageendpointsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ObjectStorageEndpointResponse
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON422      *UnprocessableContentResponse
	JSON500      *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1ObjectstorageendpointsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1ObjectstorageendpointsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *NotFoundResponse
	JSON500      *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ObjectStorageEndpointResponse
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *NotFoundResponse
	JSON500      *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *ObjectStorageEndpointResponse
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *NotFoundResponse
	JSON409      *ConflictResponse
	JSON422      *UnprocessableContentResponse
	JSON500      *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r PutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ObjectStorageAccessKeyListResponse
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *NotFoundResponse
	JSON500      *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ObjectStorageAccessKeyCreateResponse
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *NotFoundResponse
	JSON422      *UnprocessableContentResponse
	JSON500      *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *NotFoundResponse
	JSON500      *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ObjectStorageAccessKeyResponse
	JSON400      *BadRequestResponse
	JSON401      *UnauthorizedResponse
	JSON403      *ForbiddenResponse
	JSON404      *NotFoundResponse
	JSON500      *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiVersionResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ServiceVersionResponse
	JSON401      *UnauthorizedResponse
	JSON500      *InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetApiVersionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiVersionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetApiV1ObjectstorageendpointclassesWithResponse request returning *GetApiV1ObjectstorageendpointclassesResponse
func (c *ClientWithResponses) GetApiV1ObjectstorageendpointclassesWithResponse(ctx context.Context, params *GetApiV1ObjectstorageendpointclassesParams, reqEditors ...RequestEditorFn) (*GetApiV1ObjectstorageendpointclassesResponse, error) {
	rsp, err := c.GetApiV1Objectstorageendpointclasses(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ObjectstorageendpointclassesResponse(rsp)
}

// GetApiV1ObjectstorageendpointsWithResponse request returning *GetApiV1ObjectstorageendpointsResponse
func (c *ClientWithResponses) GetApiV1ObjectstorageendpointsWithResponse(ctx context.Context, params *GetApiV1ObjectstorageendpointsParams, reqEditors ...RequestEditorFn) (*GetApiV1ObjectstorageendpointsResponse, error) {
	rsp, err := c.GetApiV1Objectstorageendpoints(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ObjectstorageendpointsResponse(rsp)
}

// PostApiV1ObjectstorageendpointsWithBodyWithResponse request with arbitrary body returning *PostApiV1ObjectstorageendpointsResponse
func (c *ClientWithResponses) PostApiV1ObjectstorageendpointsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ObjectstorageendpointsResponse, error) {
	rsp, err := c.PostApiV1ObjectstorageendpointsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ObjectstorageendpointsResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1ObjectstorageendpointsWithResponse(ctx context.Context, body PostApiV1ObjectstorageendpointsJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ObjectstorageendpointsResponse, error) {
	rsp, err := c.PostApiV1Objectstorageendpoints(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ObjectstorageendpointsResponse(rsp)
}

// DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse request returning *DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse
func (c *ClientWithResponses) DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse, error) {
	rsp, err := c.DeleteApiV1ObjectstorageendpointsObjectStorageEndpointID(ctx, objectStorageEndpointID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse(rsp)
}

// GetApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse request returning *GetApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse
func (c *ClientWithResponses) GetApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*GetApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse, error) {
	rsp, err := c.GetApiV1ObjectstorageendpointsObjectStorageEndpointID(ctx, objectStorageEndpointID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse(rsp)
}

// PutApiV1ObjectstorageendpointsObjectStorageEndpointIDWithBodyWithResponse request with arbitrary body returning *PutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse
func (c *ClientWithResponses) PutApiV1ObjectstorageendpointsObjectStorageEndpointIDWithBodyWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse, error) {
	rsp, err := c.PutApiV1ObjectstorageendpointsObjectStorageEndpointIDWithBody(ctx, objectStorageEndpointID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse(rsp)
}

func (c *ClientWithResponses) PutApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, body PutApiV1ObjectstorageendpointsObjectStorageEndpointIDJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse, error) {
	rsp, err := c.PutApiV1ObjectstorageendpointsObjectStorageEndpointID(ctx, objectStorageEndpointID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse(rsp)
}

// GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithResponse request returning *GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse
func (c *ClientWithResponses) GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, reqEditors ...RequestEditorFn) (*GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse, error) {
	rsp, err := c.GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeys(ctx, objectStorageEndpointID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse(rsp)
}

// PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithBodyWithResponse request with arbitrary body returning *PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse
func (c *ClientWithResponses) PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithBodyWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse, error) {
	rsp, err := c.PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithBody(ctx, objectStorageEndpointID, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse(rsp)
}

func (c *ClientWithResponses) PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, body PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse, error) {
	rsp, err := c.PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeys(ctx, objectStorageEndpointID, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse(rsp)
}

// DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDWithResponse request returning *DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse
func (c *ClientWithResponses) DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, objectStorageAccessKeyID ObjectStorageAccessKeyIDParameter, reqEditors ...RequestEditorFn) (*DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse, error) {
	rsp, err := c.DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyID(ctx, objectStorageEndpointID, objectStorageAccessKeyID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse(rsp)
}

// GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDWithResponse request returning *GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse
func (c *ClientWithResponses) GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDWithResponse(ctx context.Context, objectStorageEndpointID ObjectStorageEndpointIDParameter, objectStorageAccessKeyID ObjectStorageAccessKeyIDParameter, reqEditors ...RequestEditorFn) (*GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse, error) {
	rsp, err := c.GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyID(ctx, objectStorageEndpointID, objectStorageAccessKeyID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse(rsp)
}

// GetApiVersionWithResponse request returning *GetApiVersionResponse
func (c *ClientWithResponses) GetApiVersionWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiVersionResponse, error) {
	rsp, err := c.GetApiVersion(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiVersionResponse(rsp)
}

// ParseGetApiV1ObjectstorageendpointclassesResponse parses an HTTP response from a GetApiV1ObjectstorageendpointclassesWithResponse call
func ParseGetApiV1ObjectstorageendpointclassesResponse(rsp *http.Response) (*GetApiV1ObjectstorageendpointclassesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ObjectstorageendpointclassesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ObjectStorageEndpointClassListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1ObjectstorageendpointsResponse parses an HTTP response from a GetApiV1ObjectstorageendpointsWithResponse call
func ParseGetApiV1ObjectstorageendpointsResponse(rsp *http.Response) (*GetApiV1ObjectstorageendpointsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ObjectstorageendpointsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ObjectStorageEndpointListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV1ObjectstorageendpointsResponse parses an HTTP response from a PostApiV1ObjectstorageendpointsWithResponse call
func ParsePostApiV1ObjectstorageendpointsResponse(rsp *http.Response) (*PostApiV1ObjectstorageendpointsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1ObjectstorageendpointsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ObjectStorageEndpointResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableContentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse parses an HTTP response from a DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse call
func ParseDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse(rsp *http.Response) (*DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse parses an HTTP response from a GetApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse call
func ParseGetApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse(rsp *http.Response) (*GetApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ObjectStorageEndpointResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse parses an HTTP response from a PutApiV1ObjectstorageendpointsObjectStorageEndpointIDWithResponse call
func ParsePutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse(rsp *http.Response) (*PutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutApiV1ObjectstorageendpointsObjectStorageEndpointIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest ObjectStorageEndpointResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ConflictResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableContentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse parses an HTTP response from a GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithResponse call
func ParseGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse(rsp *http.Response) (*GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ObjectStorageAccessKeyListResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse parses an HTTP response from a PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysWithResponse call
func ParsePostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse(rsp *http.Response) (*PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ObjectStorageAccessKeyCreateResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest UnprocessableContentResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse parses an HTTP response from a DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDWithResponse call
func ParseDeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse(rsp *http.Response) (*DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse parses an HTTP response from a GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDWithResponse call
func ParseGetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse(rsp *http.Response) (*GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiV1ObjectstorageendpointsObjectStorageEndpointIDAccesskeysObjectStorageAccessKeyIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ObjectStorageAccessKeyResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetApiVersionResponse parses an HTTP response from a GetApiVersionWithResponse call
func ParseGetApiVersionResponse(rsp *http.Response) (*GetApiVersionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiVersionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ServiceVersionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
