// Package reservation provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package reservation

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	externalRef0 "github.com/nscaledev/nscale-sdk-go/common"
	externalRef1 "github.com/nscaledev/nscale-sdk-go/region"
	"github.com/oapi-codegen/runtime"
)

const (
	Oauth2AuthenticationScopes = "oauth2Authentication.Scopes"
)

// Defines values for GpuVendorV2.
const (
	AMD    GpuVendorV2 = "AMD"
	NVIDIA GpuVendorV2 = "NVIDIA"
)

// Defines values for PlacementPolicyV2.
const (
	Pack   PlacementPolicyV2 = "pack"
	Spread PlacementPolicyV2 = "spread"
)

// Defines values for WhenUnsatisfiableV2.
const (
	BestEffort WhenUnsatisfiableV2 = "bestEffort"
	Fail       WhenUnsatisfiableV2 = "fail"
)

// GpuVendorV2 The GPU vendor.
type GpuVendorV2 string

// KubernetesNameParameter A Kubernetes name. Must be a valid DNS label containing only lower case characters, numbers or hyphens, start and end with a character or number, and be at most 63 characters in length.
type KubernetesNameParameter = string

// PlacementConstraintsV2 Scheduling policy applied when selecting hosts from the reservation.
type PlacementConstraintsV2 struct {
	// MaxSkew Maximum difference in host count between any two domains.
	// Applicable only when policy is spread.
	MaxSkew *int `json:"maxSkew,omitempty"`

	// MinDomains Minimum number of domains that must receive at least one selected
	// host. Applicable only when policy is spread. Must be less than or
	// equal to count.
	MinDomains *int `json:"minDomains,omitempty"`

	// Policy Pack fills domains sequentially, maximising locality. Spread
	// distributes hosts as evenly as possible across domains.
	Policy PlacementPolicyV2 `json:"policy"`

	// WhenUnsatisfiable Fail returns an error if the constraint cannot be fully satisfied.
	// Best effort applies the constraint as closely as it can.
	WhenUnsatisfiable *WhenUnsatisfiableV2 `json:"whenUnsatisfiable,omitempty"`
}

// PlacementPolicyV2 Pack fills domains sequentially, maximising locality. Spread
// distributes hosts as evenly as possible across domains.
type PlacementPolicyV2 string

// PlacementServerIDParameter An opaque public Placement server ID.
type PlacementServerIDParameter = string

// PlacementServerNetworkingV2 Region server networking options applied to each pinned server.
type PlacementServerNetworkingV2 struct {
	// AllowedSourceAddresses A list of network prefixes that are allowed to egress from the
	// server. By default, only packets from the server's network
	// interface's IP address are allowed to enter the network.
	AllowedSourceAddresses *[]string `json:"allowedSourceAddresses,omitempty"`

	// PublicIP Whether or not to provision a public IP.
	PublicIP *bool `json:"publicIP,omitempty"`

	// SecurityGroups A list of security group IDs.
	SecurityGroups *[]string `json:"securityGroups,omitempty"`
}

// PlacementServerSpecV2 Region server options applied to each pinned server.
type PlacementServerSpecV2 struct {
	// ImageId The image to use for each pinned server.
	ImageId string `json:"imageId"`

	// Networking Region server networking options applied to each pinned server.
	Networking *PlacementServerNetworkingV2 `json:"networking,omitempty"`

	// SshCertificateAuthorityId The SSH certificate authority ID.
	SshCertificateAuthorityId *string `json:"sshCertificateAuthorityId,omitempty"`

	// UserData Contains base64-encoded configuration information or scripts to
	// use upon launch.
	UserData *[]byte `json:"userData,omitempty"`
}

// PlacementServerV2Read A placement server.
type PlacementServerV2Read struct {
	// Metadata Metadata required by project scoped resource reads.
	Metadata externalRef0.ProjectScopedResourceReadMetadata `json:"metadata"`

	// Status Read only runtime status information about a placement server.
	Status PlacementServerV2Status `json:"status"`
}

// PlacementServerV2Status Read only runtime status information about a placement server.
type PlacementServerV2Status struct {
	// MacAddress The MAC address of the server.
	MacAddress *string `json:"macAddress,omitempty"`

	// NetworkId The network the placement server belongs to.
	NetworkId string `json:"networkId"`

	// PlacementId The placement that owns this server.
	PlacementId string `json:"placementId"`

	// PowerState The lifecycle phase of an instance.
	PowerState *externalRef1.InstanceLifecyclePhase `json:"powerState,omitempty"`

	// PrivateIP The private IP address of the server.
	PrivateIP *string `json:"privateIP,omitempty"`

	// PublicIP The public IP address of the server.
	PublicIP *string `json:"publicIP,omitempty"`

	// RegionId The region the placement server belongs to.
	RegionId string `json:"regionId"`

	// ReservationId The reservation the placement server allocates from.
	ReservationId string `json:"reservationId"`
}

// PlacementServersV2Read A list of placement servers.
type PlacementServersV2Read = []PlacementServerV2Read

// PlacementV2Create A placement creation request.
type PlacementV2Create struct {
	// Metadata Metadata required for all API resource reads and writes.
	Metadata externalRef0.ResourceWriteMetadata `json:"metadata"`

	// Spec A placement creation specification.
	Spec PlacementV2CreateSpec `json:"spec"`
}

// PlacementV2CreateSpec defines model for placementV2CreateSpec.
type PlacementV2CreateSpec struct {
	// Constraints Scheduling policy applied when selecting hosts from the reservation.
	Constraints PlacementConstraintsV2 `json:"constraints"`

	// Count Number of hosts to allocate from the reservation.
	Count int `json:"count"`

	// NetworkId Network to attach instances to. Also determines the InfiniBand
	// partition boundary; all hosts in a placement share a single
	// partition key.
	NetworkId string `json:"networkId"`

	// ReservationId The reservation to allocate hosts from.
	ReservationId string `json:"reservationId"`

	// ServerSpec Region server options applied to each pinned server.
	ServerSpec PlacementServerSpecV2 `json:"serverSpec"`
}

// PlacementV2Read A placement.
type PlacementV2Read struct {
	// Metadata Metadata required by project scoped resource reads.
	Metadata externalRef0.ProjectScopedResourceReadMetadata `json:"metadata"`

	// Spec A placement's specification.
	Spec PlacementV2Spec `json:"spec"`

	// Status Read only status information about a placement.
	Status PlacementV2Status `json:"status"`
}

// PlacementV2Spec A placement's specification.
type PlacementV2Spec struct {
	// Constraints Scheduling policy applied when selecting hosts from the reservation.
	Constraints PlacementConstraintsV2 `json:"constraints"`

	// Count Number of hosts to allocate from the reservation.
	Count int `json:"count"`

	// ServerSpec Region server options applied to each pinned server.
	ServerSpec PlacementServerSpecV2 `json:"serverSpec"`
}

// PlacementV2Status Read only status information about a placement.
type PlacementV2Status struct {
	// NetworkId The network the placement belongs to.
	NetworkId string `json:"networkId"`

	// ReadyHostCount Number of hosts whose Region server resources are ready.
	ReadyHostCount *int `json:"readyHostCount,omitempty"`

	// RegionId The region the placement belongs to.
	RegionId string `json:"regionId"`

	// ReservationId The reservation the placement allocates from.
	ReservationId string `json:"reservationId"`
}

// PlacementsV2Read A list of placements.
type PlacementsV2Read = []PlacementV2Read

// ReservationUnitGpuV2 GPU specification for one host in a reservation unit.
type ReservationUnitGpuV2 struct {
	// LogicalCount The logical number of GPUs available on one host.
	LogicalCount int `json:"logicalCount"`

	// Memory GPU memory in GiB for one GPU.
	Memory int `json:"memory"`

	// Model A GPU model.
	Model string `json:"model"`

	// PhysicalCount The physical number of GPUs available on one host.
	PhysicalCount int `json:"physicalCount"`

	// Vendor The GPU vendor.
	Vendor GpuVendorV2 `json:"vendor"`
}

// ReservationUnitHostV2 Region flavor capacity for one host in a reservation unit.
type ReservationUnitHostV2 struct {
	// Cpus The number of CPUs on one host.
	Cpus int `json:"cpus"`

	// Disk The amount of ephemeral disk in GB on one host.
	Disk int `json:"disk"`

	// Gpu GPU specification for one host in a reservation unit.
	Gpu ReservationUnitGpuV2 `json:"gpu"`

	// Memory The amount of memory in GiB on one host.
	Memory int `json:"memory"`
}

// ReservationUnitV2 A regional accelerator reservation unit offering.
type ReservationUnitV2 struct {
	// Accelerator Public accelerator model or family, for example GB300.
	Accelerator string `json:"accelerator"`

	// AvailableUnitCount Number of complete, currently unclaimed reservation units.
	AvailableUnitCount int `json:"availableUnitCount"`

	// CpusPerUnit Total CPUs claimed by one reservation unit.
	CpusPerUnit int `json:"cpusPerUnit"`

	// DeviceTypeResourceClass Expected Fleet Manager device type resource class for selected hosts.
	DeviceTypeResourceClass string `json:"deviceTypeResourceClass"`

	// GpuMemoryPerUnit Total GPU memory in GiB claimed by one reservation unit.
	GpuMemoryPerUnit int `json:"gpuMemoryPerUnit"`

	// GpusPerUnit Total GPUs claimed by one reservation unit.
	GpusPerUnit int `json:"gpusPerUnit"`

	// Host Region flavor capacity for one host in a reservation unit.
	Host ReservationUnitHostV2 `json:"host"`

	// HostsPerUnit Number of hosts claimed by one reservation unit.
	HostsPerUnit int `json:"hostsPerUnit"`

	// LargestContiguousUnitCount Largest contiguous reservation-unit count currently satisfiable.
	LargestContiguousUnitCount int `json:"largestContiguousUnitCount"`

	// MachineFlavorId Region machine flavor resolved for this reservation unit.
	MachineFlavorId string `json:"machineFlavorId"`

	// MemoryPerUnit Total memory in GiB claimed by one reservation unit.
	MemoryPerUnit int `json:"memoryPerUnit"`

	// RegionId The region where this reservation unit is offered.
	RegionId string `json:"regionId"`

	// TotalCount Number of complete reservation units in the regional offering.
	TotalCount int `json:"totalCount"`

	// Unit Public reservation granularity, for example NVL72.
	Unit string `json:"unit"`
}

// ReservationUnitsV2 A list of regional accelerator reservation unit offerings.
type ReservationUnitsV2 = []ReservationUnitV2

// ReservationV2Create A reservation creation request.
type ReservationV2Create struct {
	// Metadata Metadata required for all API resource reads and writes.
	Metadata externalRef0.ResourceWriteMetadata `json:"metadata"`

	// Spec A reservation creation specification.
	Spec ReservationV2CreateSpec `json:"spec"`
}

// ReservationV2CreateSpec defines model for reservationV2CreateSpec.
type ReservationV2CreateSpec struct {
	// Accelerator Public accelerator model or family to reserve.
	Accelerator string `json:"accelerator"`

	// Count Number of reservation units to reserve.
	Count int `json:"count"`

	// OrganizationId The organization to provision the reservation in.
	OrganizationId string `json:"organizationId"`

	// ProjectId The project to provision the reservation in.
	ProjectId string `json:"projectId"`

	// RegionId The region to reserve capacity in.
	RegionId string `json:"regionId"`

	// Unit Public reservation granularity to reserve.
	Unit string `json:"unit"`
}

// ReservationV2Read A reservation.
type ReservationV2Read struct {
	// Metadata Metadata required by project scoped resource reads.
	Metadata externalRef0.ProjectScopedResourceReadMetadata `json:"metadata"`

	// Spec A reservation's specification.
	Spec ReservationV2Spec `json:"spec"`

	// Status Read only status information about a reservation.
	Status ReservationV2Status `json:"status"`
}

// ReservationV2Spec A reservation's specification.
type ReservationV2Spec struct {
	// Accelerator Public accelerator model or family to reserve.
	Accelerator string `json:"accelerator"`

	// Count Number of reservation units to reserve.
	Count int `json:"count"`

	// RegionId The region to reserve capacity in.
	RegionId string `json:"regionId"`

	// Unit Public reservation granularity to reserve.
	Unit string `json:"unit"`
}

// ReservationV2Status Read only status information about a reservation.
type ReservationV2Status struct {
	// ClaimedUnitCount Number of reservation units successfully claimed.
	ClaimedUnitCount int `json:"claimedUnitCount"`

	// MachineFlavorId Resolved Region machine flavor used for pinned servers.
	MachineFlavorId string `json:"machineFlavorId"`

	// TopologyHash Hash of the claimed topology projection accepted by the reservation.
	TopologyHash *string `json:"topologyHash,omitempty"`

	// TopologyObservedAt Time when the claimed topology projection was last observed.
	TopologyObservedAt *time.Time `json:"topologyObservedAt,omitempty"`
}

// ReservationsV2Read A list of reservations.
type ReservationsV2Read = []ReservationV2Read

// WhenUnsatisfiableV2 Fail returns an error if the constraint cannot be fully satisfied.
// Best effort applies the constraint as closely as it can.
type WhenUnsatisfiableV2 string

// AcceleratorQueryParameter defines model for acceleratorQueryParameter.
type AcceleratorQueryParameter = []string

// HardRebootParameter defines model for hardRebootParameter.
type HardRebootParameter = bool

// NetworkIDQueryParameter defines model for networkIDQueryParameter.
type NetworkIDQueryParameter = []string

// OrganizationIDQueryParameter defines model for organizationIDQueryParameter.
type OrganizationIDQueryParameter = []string

// PlacementIDParameter A Kubernetes name. Must be a valid DNS label containing only lower case characters, numbers or hyphens, start and end with a character or number, and be at most 63 characters in length.
type PlacementIDParameter = KubernetesNameParameter

// ProjectIDQueryParameter defines model for projectIDQueryParameter.
type ProjectIDQueryParameter = []string

// RegionIDQueryParameter defines model for regionIDQueryParameter.
type RegionIDQueryParameter = []string

// ReservationIDParameter A Kubernetes name. Must be a valid DNS label containing only lower case characters, numbers or hyphens, start and end with a character or number, and be at most 63 characters in length.
type ReservationIDParameter = KubernetesNameParameter

// ReservationIDQueryParameter defines model for reservationIDQueryParameter.
type ReservationIDQueryParameter = []string

// ReservationUnitQueryParameter defines model for reservationUnitQueryParameter.
type ReservationUnitQueryParameter = []string

// ServerIDParameter An opaque public Placement server ID.
type ServerIDParameter = PlacementServerIDParameter

// InsufficientCapacityResponse Generic error message, compatible with oauth2.
type InsufficientCapacityResponse = externalRef0.Error

// PlacementServerV2Response A placement server.
type PlacementServerV2Response = PlacementServerV2Read

// PlacementServersV2Response A list of placement servers.
type PlacementServersV2Response = PlacementServersV2Read

// PlacementV2Response A placement.
type PlacementV2Response = PlacementV2Read

// PlacementsV2Response A list of placements.
type PlacementsV2Response = PlacementsV2Read

// ReservationUnitsV2Response A list of regional accelerator reservation unit offerings.
type ReservationUnitsV2Response = ReservationUnitsV2

// ReservationV2Response A reservation.
type ReservationV2Response = ReservationV2Read

// ReservationsV2Response A list of reservations.
type ReservationsV2Response = ReservationsV2Read

// PlacementV2CreateRequest A placement creation request.
type PlacementV2CreateRequest = PlacementV2Create

// ReservationV2CreateRequest A reservation creation request.
type ReservationV2CreateRequest = ReservationV2Create

// ListPlacementsParams defines parameters for ListPlacements.
type ListPlacementsParams struct {
	// Tag A set of tags to match against resources in the form "name=value",
	// thus when encoded you get "?tag=foo%3Dcat&tag=bar%3Ddog".
	Tag *externalRef0.TagSelectorParameter `form:"tag,omitempty" json:"tag,omitempty"`

	// OrganizationID Allows resources to be filtered by organization.
	OrganizationID *OrganizationIDQueryParameter `form:"organizationID,omitempty" json:"organizationID,omitempty"`

	// ProjectID Allows resources to be filtered by project.
	ProjectID *ProjectIDQueryParameter `form:"projectID,omitempty" json:"projectID,omitempty"`

	// RegionID Allows resources to be filtered by region.
	RegionID *RegionIDQueryParameter `form:"regionID,omitempty" json:"regionID,omitempty"`

	// ReservationID Allows placements to be filtered by reservation.
	ReservationID *ReservationIDQueryParameter `form:"reservationID,omitempty" json:"reservationID,omitempty"`

	// NetworkID Allows placements to be filtered by network.
	NetworkID *NetworkIDQueryParameter `form:"networkID,omitempty" json:"networkID,omitempty"`
}

// RebootPlacementServerParams defines parameters for RebootPlacementServer.
type RebootPlacementServerParams struct {
	// Hard Whether the reboot is hard. Defaults to false.
	Hard *HardRebootParameter `form:"hard,omitempty" json:"hard,omitempty"`
}

// ListReservationUnitsParams defines parameters for ListReservationUnits.
type ListReservationUnitsParams struct {
	// RegionID Allows resources to be filtered by region.
	RegionID *RegionIDQueryParameter `form:"regionID,omitempty" json:"regionID,omitempty"`

	// Accelerator Allows reservation units to be filtered by accelerator model or family.
	Accelerator *AcceleratorQueryParameter `form:"accelerator,omitempty" json:"accelerator,omitempty"`

	// Unit Allows reservation units to be filtered by reservation granularity.
	Unit *ReservationUnitQueryParameter `form:"unit,omitempty" json:"unit,omitempty"`
}

// ListReservationsParams defines parameters for ListReservations.
type ListReservationsParams struct {
	// Tag A set of tags to match against resources in the form "name=value",
	// thus when encoded you get "?tag=foo%3Dcat&tag=bar%3Ddog".
	Tag *externalRef0.TagSelectorParameter `form:"tag,omitempty" json:"tag,omitempty"`

	// OrganizationID Allows resources to be filtered by organization.
	OrganizationID *OrganizationIDQueryParameter `form:"organizationID,omitempty" json:"organizationID,omitempty"`

	// ProjectID Allows resources to be filtered by project.
	ProjectID *ProjectIDQueryParameter `form:"projectID,omitempty" json:"projectID,omitempty"`

	// RegionID Allows resources to be filtered by region.
	RegionID *RegionIDQueryParameter `form:"regionID,omitempty" json:"regionID,omitempty"`
}

// CreatePlacementJSONRequestBody defines body for CreatePlacement for application/json ContentType.
type CreatePlacementJSONRequestBody = PlacementV2Create

// CreateReservationJSONRequestBody defines body for CreateReservation for application/json ContentType.
type CreateReservationJSONRequestBody = ReservationV2Create

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListPlacements request
	ListPlacements(ctx context.Context, params *ListPlacementsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePlacementWithBody request with any body
	CreatePlacementWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreatePlacement(ctx context.Context, body CreatePlacementJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeletePlacement request
	DeletePlacement(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPlacement request
	GetPlacement(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListPlacementServers request
	ListPlacementServers(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPlacementServer request
	GetPlacementServer(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RebootPlacementServer request
	RebootPlacementServer(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, params *RebootPlacementServerParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StopPlacementServer request
	StopPlacementServer(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListReservationUnits request
	ListReservationUnits(ctx context.Context, params *ListReservationUnitsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListReservations request
	ListReservations(ctx context.Context, params *ListReservationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateReservationWithBody request with any body
	CreateReservationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateReservation(ctx context.Context, body CreateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteReservation request
	DeleteReservation(ctx context.Context, reservationID ReservationIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReservation request
	GetReservation(ctx context.Context, reservationID ReservationIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListPlacements(ctx context.Context, params *ListPlacementsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPlacementsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePlacementWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePlacementRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreatePlacement(ctx context.Context, body CreatePlacementJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePlacementRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeletePlacement(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeletePlacementRequest(c.Server, placementID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPlacement(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPlacementRequest(c.Server, placementID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListPlacementServers(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPlacementServersRequest(c.Server, placementID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPlacementServer(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPlacementServerRequest(c.Server, placementID, serverID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RebootPlacementServer(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, params *RebootPlacementServerParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRebootPlacementServerRequest(c.Server, placementID, serverID, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StopPlacementServer(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStopPlacementServerRequest(c.Server, placementID, serverID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListReservationUnits(ctx context.Context, params *ListReservationUnitsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListReservationUnitsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListReservations(ctx context.Context, params *ListReservationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListReservationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateReservationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateReservationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateReservation(ctx context.Context, body CreateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateReservationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteReservation(ctx context.Context, reservationID ReservationIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteReservationRequest(c.Server, reservationID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetReservation(ctx context.Context, reservationID ReservationIDParameter, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReservationRequest(c.Server, reservationID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListPlacementsRequest generates requests for ListPlacements
func NewListPlacementsRequest(server string, params *ListPlacementsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/placements")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Tag != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tag", runtime.ParamLocationQuery, *params.Tag); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrganizationID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organizationID", runtime.ParamLocationQuery, *params.OrganizationID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ProjectID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "projectID", runtime.ParamLocationQuery, *params.ProjectID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RegionID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "regionID", runtime.ParamLocationQuery, *params.RegionID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ReservationID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "reservationID", runtime.ParamLocationQuery, *params.ReservationID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NetworkID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "networkID", runtime.ParamLocationQuery, *params.NetworkID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreatePlacementRequest calls the generic CreatePlacement builder with application/json body
func NewCreatePlacementRequest(server string, body CreatePlacementJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePlacementRequestWithBody(server, "application/json", bodyReader)
}

// NewCreatePlacementRequestWithBody generates requests for CreatePlacement with any type of body
func NewCreatePlacementRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/placements")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeletePlacementRequest generates requests for DeletePlacement
func NewDeletePlacementRequest(server string, placementID PlacementIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "placementID", runtime.ParamLocationPath, placementID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/placements/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPlacementRequest generates requests for GetPlacement
func NewGetPlacementRequest(server string, placementID PlacementIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "placementID", runtime.ParamLocationPath, placementID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/placements/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListPlacementServersRequest generates requests for ListPlacementServers
func NewListPlacementServersRequest(server string, placementID PlacementIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "placementID", runtime.ParamLocationPath, placementID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/placements/%s/servers", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetPlacementServerRequest generates requests for GetPlacementServer
func NewGetPlacementServerRequest(server string, placementID PlacementIDParameter, serverID ServerIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "placementID", runtime.ParamLocationPath, placementID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "serverID", runtime.ParamLocationPath, serverID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/placements/%s/servers/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRebootPlacementServerRequest generates requests for RebootPlacementServer
func NewRebootPlacementServerRequest(server string, placementID PlacementIDParameter, serverID ServerIDParameter, params *RebootPlacementServerParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "placementID", runtime.ParamLocationPath, placementID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "serverID", runtime.ParamLocationPath, serverID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/placements/%s/servers/%s/reboot", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Hard != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "hard", runtime.ParamLocationQuery, *params.Hard); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStopPlacementServerRequest generates requests for StopPlacementServer
func NewStopPlacementServerRequest(server string, placementID PlacementIDParameter, serverID ServerIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "placementID", runtime.ParamLocationPath, placementID)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "serverID", runtime.ParamLocationPath, serverID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/placements/%s/servers/%s/stop", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListReservationUnitsRequest generates requests for ListReservationUnits
func NewListReservationUnitsRequest(server string, params *ListReservationUnitsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/reservation-units")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.RegionID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "regionID", runtime.ParamLocationQuery, *params.RegionID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Accelerator != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "accelerator", runtime.ParamLocationQuery, *params.Accelerator); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Unit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "unit", runtime.ParamLocationQuery, *params.Unit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListReservationsRequest generates requests for ListReservations
func NewListReservationsRequest(server string, params *ListReservationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/reservations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Tag != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tag", runtime.ParamLocationQuery, *params.Tag); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.OrganizationID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "organizationID", runtime.ParamLocationQuery, *params.OrganizationID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.ProjectID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "projectID", runtime.ParamLocationQuery, *params.ProjectID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.RegionID != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "regionID", runtime.ParamLocationQuery, *params.RegionID); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateReservationRequest calls the generic CreateReservation builder with application/json body
func NewCreateReservationRequest(server string, body CreateReservationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateReservationRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateReservationRequestWithBody generates requests for CreateReservation with any type of body
func NewCreateReservationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/reservations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteReservationRequest generates requests for DeleteReservation
func NewDeleteReservationRequest(server string, reservationID ReservationIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "reservationID", runtime.ParamLocationPath, reservationID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/reservations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetReservationRequest generates requests for GetReservation
func NewGetReservationRequest(server string, reservationID ReservationIDParameter) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "reservationID", runtime.ParamLocationPath, reservationID)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v2/reservations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListPlacementsWithResponse request
	ListPlacementsWithResponse(ctx context.Context, params *ListPlacementsParams, reqEditors ...RequestEditorFn) (*ListPlacementsResponse, error)

	// CreatePlacementWithBodyWithResponse request with any body
	CreatePlacementWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePlacementResponse, error)

	CreatePlacementWithResponse(ctx context.Context, body CreatePlacementJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePlacementResponse, error)

	// DeletePlacementWithResponse request
	DeletePlacementWithResponse(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*DeletePlacementResponse, error)

	// GetPlacementWithResponse request
	GetPlacementWithResponse(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*GetPlacementResponse, error)

	// ListPlacementServersWithResponse request
	ListPlacementServersWithResponse(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*ListPlacementServersResponse, error)

	// GetPlacementServerWithResponse request
	GetPlacementServerWithResponse(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, reqEditors ...RequestEditorFn) (*GetPlacementServerResponse, error)

	// RebootPlacementServerWithResponse request
	RebootPlacementServerWithResponse(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, params *RebootPlacementServerParams, reqEditors ...RequestEditorFn) (*RebootPlacementServerResponse, error)

	// StopPlacementServerWithResponse request
	StopPlacementServerWithResponse(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, reqEditors ...RequestEditorFn) (*StopPlacementServerResponse, error)

	// ListReservationUnitsWithResponse request
	ListReservationUnitsWithResponse(ctx context.Context, params *ListReservationUnitsParams, reqEditors ...RequestEditorFn) (*ListReservationUnitsResponse, error)

	// ListReservationsWithResponse request
	ListReservationsWithResponse(ctx context.Context, params *ListReservationsParams, reqEditors ...RequestEditorFn) (*ListReservationsResponse, error)

	// CreateReservationWithBodyWithResponse request with any body
	CreateReservationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateReservationResponse, error)

	CreateReservationWithResponse(ctx context.Context, body CreateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateReservationResponse, error)

	// DeleteReservationWithResponse request
	DeleteReservationWithResponse(ctx context.Context, reservationID ReservationIDParameter, reqEditors ...RequestEditorFn) (*DeleteReservationResponse, error)

	// GetReservationWithResponse request
	GetReservationWithResponse(ctx context.Context, reservationID ReservationIDParameter, reqEditors ...RequestEditorFn) (*GetReservationResponse, error)
}

type ListPlacementsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PlacementsV2Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListPlacementsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPlacementsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreatePlacementResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *PlacementV2Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON404      *externalRef0.NotFoundResponse
	JSON409      *externalRef0.ConflictResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r CreatePlacementResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePlacementResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeletePlacementResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON404      *externalRef0.NotFoundResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeletePlacementResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeletePlacementResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPlacementResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PlacementV2Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON404      *externalRef0.NotFoundResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetPlacementResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPlacementResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListPlacementServersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PlacementServersV2Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON404      *externalRef0.NotFoundResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListPlacementServersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPlacementServersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPlacementServerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PlacementServerV2Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON404      *externalRef0.NotFoundResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetPlacementServerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPlacementServerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RebootPlacementServerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON404      *externalRef0.NotFoundResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r RebootPlacementServerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RebootPlacementServerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StopPlacementServerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON404      *externalRef0.NotFoundResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r StopPlacementServerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StopPlacementServerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListReservationUnitsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ReservationUnitsV2Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListReservationUnitsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListReservationUnitsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListReservationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ReservationsV2Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r ListReservationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListReservationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateReservationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *ReservationV2Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON404      *externalRef0.NotFoundResponse
	JSON500      *externalRef0.InternalServerErrorResponse
	JSON507      *InsufficientCapacityResponse
}

// Status returns HTTPResponse.Status
func (r CreateReservationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateReservationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteReservationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON404      *externalRef0.NotFoundResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r DeleteReservationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteReservationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetReservationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ReservationV2Response
	JSON400      *externalRef0.BadRequestResponse
	JSON401      *externalRef0.UnauthorizedResponse
	JSON403      *externalRef0.ForbiddenResponse
	JSON404      *externalRef0.NotFoundResponse
	JSON500      *externalRef0.InternalServerErrorResponse
}

// Status returns HTTPResponse.Status
func (r GetReservationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReservationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListPlacementsWithResponse request returning *ListPlacementsResponse
func (c *ClientWithResponses) ListPlacementsWithResponse(ctx context.Context, params *ListPlacementsParams, reqEditors ...RequestEditorFn) (*ListPlacementsResponse, error) {
	rsp, err := c.ListPlacements(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPlacementsResponse(rsp)
}

// CreatePlacementWithBodyWithResponse request with arbitrary body returning *CreatePlacementResponse
func (c *ClientWithResponses) CreatePlacementWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePlacementResponse, error) {
	rsp, err := c.CreatePlacementWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePlacementResponse(rsp)
}

func (c *ClientWithResponses) CreatePlacementWithResponse(ctx context.Context, body CreatePlacementJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePlacementResponse, error) {
	rsp, err := c.CreatePlacement(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePlacementResponse(rsp)
}

// DeletePlacementWithResponse request returning *DeletePlacementResponse
func (c *ClientWithResponses) DeletePlacementWithResponse(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*DeletePlacementResponse, error) {
	rsp, err := c.DeletePlacement(ctx, placementID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeletePlacementResponse(rsp)
}

// GetPlacementWithResponse request returning *GetPlacementResponse
func (c *ClientWithResponses) GetPlacementWithResponse(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*GetPlacementResponse, error) {
	rsp, err := c.GetPlacement(ctx, placementID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPlacementResponse(rsp)
}

// ListPlacementServersWithResponse request returning *ListPlacementServersResponse
func (c *ClientWithResponses) ListPlacementServersWithResponse(ctx context.Context, placementID PlacementIDParameter, reqEditors ...RequestEditorFn) (*ListPlacementServersResponse, error) {
	rsp, err := c.ListPlacementServers(ctx, placementID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPlacementServersResponse(rsp)
}

// GetPlacementServerWithResponse request returning *GetPlacementServerResponse
func (c *ClientWithResponses) GetPlacementServerWithResponse(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, reqEditors ...RequestEditorFn) (*GetPlacementServerResponse, error) {
	rsp, err := c.GetPlacementServer(ctx, placementID, serverID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPlacementServerResponse(rsp)
}

// RebootPlacementServerWithResponse request returning *RebootPlacementServerResponse
func (c *ClientWithResponses) RebootPlacementServerWithResponse(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, params *RebootPlacementServerParams, reqEditors ...RequestEditorFn) (*RebootPlacementServerResponse, error) {
	rsp, err := c.RebootPlacementServer(ctx, placementID, serverID, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRebootPlacementServerResponse(rsp)
}

// StopPlacementServerWithResponse request returning *StopPlacementServerResponse
func (c *ClientWithResponses) StopPlacementServerWithResponse(ctx context.Context, placementID PlacementIDParameter, serverID ServerIDParameter, reqEditors ...RequestEditorFn) (*StopPlacementServerResponse, error) {
	rsp, err := c.StopPlacementServer(ctx, placementID, serverID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStopPlacementServerResponse(rsp)
}

// ListReservationUnitsWithResponse request returning *ListReservationUnitsResponse
func (c *ClientWithResponses) ListReservationUnitsWithResponse(ctx context.Context, params *ListReservationUnitsParams, reqEditors ...RequestEditorFn) (*ListReservationUnitsResponse, error) {
	rsp, err := c.ListReservationUnits(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListReservationUnitsResponse(rsp)
}

// ListReservationsWithResponse request returning *ListReservationsResponse
func (c *ClientWithResponses) ListReservationsWithResponse(ctx context.Context, params *ListReservationsParams, reqEditors ...RequestEditorFn) (*ListReservationsResponse, error) {
	rsp, err := c.ListReservations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListReservationsResponse(rsp)
}

// CreateReservationWithBodyWithResponse request with arbitrary body returning *CreateReservationResponse
func (c *ClientWithResponses) CreateReservationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateReservationResponse, error) {
	rsp, err := c.CreateReservationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateReservationResponse(rsp)
}

func (c *ClientWithResponses) CreateReservationWithResponse(ctx context.Context, body CreateReservationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateReservationResponse, error) {
	rsp, err := c.CreateReservation(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateReservationResponse(rsp)
}

// DeleteReservationWithResponse request returning *DeleteReservationResponse
func (c *ClientWithResponses) DeleteReservationWithResponse(ctx context.Context, reservationID ReservationIDParameter, reqEditors ...RequestEditorFn) (*DeleteReservationResponse, error) {
	rsp, err := c.DeleteReservation(ctx, reservationID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteReservationResponse(rsp)
}

// GetReservationWithResponse request returning *GetReservationResponse
func (c *ClientWithResponses) GetReservationWithResponse(ctx context.Context, reservationID ReservationIDParameter, reqEditors ...RequestEditorFn) (*GetReservationResponse, error) {
	rsp, err := c.GetReservation(ctx, reservationID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReservationResponse(rsp)
}

// ParseListPlacementsResponse parses an HTTP response from a ListPlacementsWithResponse call
func ParseListPlacementsResponse(rsp *http.Response) (*ListPlacementsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPlacementsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PlacementsV2Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreatePlacementResponse parses an HTTP response from a CreatePlacementWithResponse call
func ParseCreatePlacementResponse(rsp *http.Response) (*CreatePlacementResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePlacementResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest PlacementV2Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest externalRef0.ConflictResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseDeletePlacementResponse parses an HTTP response from a DeletePlacementWithResponse call
func ParseDeletePlacementResponse(rsp *http.Response) (*DeletePlacementResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeletePlacementResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetPlacementResponse parses an HTTP response from a GetPlacementWithResponse call
func ParseGetPlacementResponse(rsp *http.Response) (*GetPlacementResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPlacementResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PlacementV2Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListPlacementServersResponse parses an HTTP response from a ListPlacementServersWithResponse call
func ParseListPlacementServersResponse(rsp *http.Response) (*ListPlacementServersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPlacementServersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PlacementServersV2Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetPlacementServerResponse parses an HTTP response from a GetPlacementServerWithResponse call
func ParseGetPlacementServerResponse(rsp *http.Response) (*GetPlacementServerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPlacementServerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PlacementServerV2Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseRebootPlacementServerResponse parses an HTTP response from a RebootPlacementServerWithResponse call
func ParseRebootPlacementServerResponse(rsp *http.Response) (*RebootPlacementServerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RebootPlacementServerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseStopPlacementServerResponse parses an HTTP response from a StopPlacementServerWithResponse call
func ParseStopPlacementServerResponse(rsp *http.Response) (*StopPlacementServerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StopPlacementServerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListReservationUnitsResponse parses an HTTP response from a ListReservationUnitsWithResponse call
func ParseListReservationUnitsResponse(rsp *http.Response) (*ListReservationUnitsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListReservationUnitsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReservationUnitsV2Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseListReservationsResponse parses an HTTP response from a ListReservationsWithResponse call
func ParseListReservationsResponse(rsp *http.Response) (*ListReservationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListReservationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReservationsV2Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseCreateReservationResponse parses an HTTP response from a CreateReservationWithResponse call
func ParseCreateReservationResponse(rsp *http.Response) (*CreateReservationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateReservationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest ReservationV2Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 507:
		var dest InsufficientCapacityResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON507 = &dest

	}

	return response, nil
}

// ParseDeleteReservationResponse parses an HTTP response from a DeleteReservationWithResponse call
func ParseDeleteReservationResponse(rsp *http.Response) (*DeleteReservationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteReservationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseGetReservationResponse parses an HTTP response from a GetReservationWithResponse call
func ParseGetReservationResponse(rsp *http.Response) (*GetReservationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReservationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ReservationV2Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest externalRef0.BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest externalRef0.UnauthorizedResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest externalRef0.ForbiddenResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest externalRef0.NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest externalRef0.InternalServerErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
